version: "3.6"
services:
  item-app:
    image: wisnuwiranata/dicoding_app:v1
    container_name: item-app
    ports:
      - "80:8080"
    links:
      - item-db
    restart: on-failure
  item-db:
    image: mongo:3
    container_name: item-db
    volumes:
      - app-db:/data/db
    restart: on-failure
volumes:
  app-db: